workspace:
  base: "/woodpecker"
  path: "/"

when:
  - branch: main
    event: [push, manual]

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
