when:
  - branch: main
    event: [push, manual]

steps:
  - name: build
    image: node:20
    commands:
      - echo "Working directory -> $(pwd)"
      - ls -lah
      - sh .woodpecker/bin/build.sh
