workspace:
  base: "/woodpecker"
  path: "/"

when:
  - branch: main
    event: push
  - branch: main
    event: manual

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable
